using Gridlet.Models;
using Microsoft.Data.Sqlite;

namespace Gridlet.Sqlite;

internal static class SqliteTableImportService
{
    public static async Task<TableImportResult> ImportAsync(
        GridletConnectionContext context, string schema, string table, TableImport import,
        CancellationToken cancellationToken)
    {
        SqliteIdentifier.RequireSelectedSchema(context, schema);
        if (import.Columns.Count == 0) throw new GridletValidationException("An import needs at least one mapped column.");
        if (import.Rows.Count == 0) return new TableImportResult(0);
        if (import.Rows.Any(row => row.Count != import.Columns.Count))
            throw new GridletValidationException("Every imported row must have one value per mapped column.");

        await using var connection = await SqliteConnectionFactory.OpenAsync(context, cancellationToken);
        var definition = await SqliteSchemaReader.LoadTableDefinitionAsync(connection, schema, table, cancellationToken);
        if (definition.Object.Type != DbObjectType.Table || definition.Object.IsInternal ||
            definition.Object.SubKind is "virtual" or "shadow")
            throw new GridletValidationException($"{schema}.{table} is not a table Gridlet can import into.");

        var columns = ValidateColumns(import.Columns, definition);
        await using var transaction = (SqliteTransaction)await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            // Keep batches comfortably below SQLite's variable limit across supported builds.
            var batchSize = Math.Max(1, Math.Min(500, 900 / columns.Count));
            for (var offset = 0; offset < import.Rows.Count; offset += batchSize)
            {
                var count = Math.Min(batchSize, import.Rows.Count - offset);
                await using var command = connection.CreateCommand();
                command.Transaction = transaction;
                var values = new string[count];
                for (var rowIndex = 0; rowIndex < count; rowIndex++)
                {
                    var parameters = new string[columns.Count];
                    for (var columnIndex = 0; columnIndex < columns.Count; columnIndex++)
                    {
                        var parameterName = $"@value{rowIndex}_{columnIndex}";
                        parameters[columnIndex] = parameterName;
                        command.Parameters.Add(new SqliteParameter(
                            parameterName, import.Rows[offset + rowIndex][columnIndex] ?? DBNull.Value));
                    }
                    values[rowIndex] = $"({string.Join(", ", parameters)})";
                }
                command.CommandText = $"INSERT INTO {SqliteIdentifier.QuoteQualified(schema, table)} " +
                    $"({string.Join(", ", columns.Select(SqliteIdentifier.Quote))}) VALUES " +
                    $"{string.Join(", ", values)};";
                await command.ExecuteNonQueryAsync(cancellationToken);
            }
            await transaction.CommitAsync(cancellationToken);
            return new TableImportResult(import.Rows.Count);
        }
        catch (SqliteException ex)
        {
            await transaction.RollbackAsync(CancellationToken.None);
            throw new GridletQueryException(ex.Message, ex);
        }
    }

    private static IReadOnlyList<string> ValidateColumns(
        IReadOnlyList<string> requested, TableDefinition definition)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var columns = new List<string>(requested.Count);
        foreach (var name in requested)
        {
            var column = definition.Columns.FirstOrDefault(candidate =>
                string.Equals(candidate.Name, name, StringComparison.OrdinalIgnoreCase))
                ?? throw new GridletValidationException($"Column '{name}' does not exist on {definition.Object.Schema}.{definition.Object.Name}.");
            if (!seen.Add(column.Name)) throw new GridletValidationException($"Column '{column.Name}' is mapped more than once.");
            if (column.IsIdentity || column.IsComputed || column.IsHidden)
                throw new GridletValidationException($"Column '{column.Name}' cannot be imported because it is generated by SQLite.");
            columns.Add(column.Name);
        }
        return columns;
    }
}
